const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '..');
// Synthetic feed entries exercise parser and UI states without depending on live news.
const feed = `<feed xmlns="http://www.w3.org/2005/Atom">
<entry><title>Climate &amp; context</title><link rel="alternate" href="https://www.vox.com/climate/test"/><author><name>Test Author</name></author><published>2026-10-01T10:00:00Z</published><category term="Climate"/><content type="html"><![CDATA[<p>A synthetic article about energy.</p><img src="https://example.com/photo.jpg" onerror="alert(1)"><script>alert(1)</script><a href="javascript:alert(1)">Unsafe</a><a href="/news">Source</a><iframe src="https://example.com"></iframe>]]></content></entry>
<entry><title>Science story</title><link href="https://www.vox.com/science/test"/><published>2026-10-02T10:00:00Z</published><content><![CDATA[<p>Another synthetic test story.</p>]]></content></entry>
<entry><title>Unknown date</title><link href="https://www.vox.com/other/test"/><published>bad</published><summary><![CDATA[<p>Summary only.</p>]]></summary></entry>
</feed>`;
function setup(options = {}) {
  const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), { url: 'https://reader.test/rssfeed/', runScripts: 'outside-only' });
  const w = dom.window;
  w.matchMedia = () => ({ matches: true });
  w.fetch = options.fetch || (async () => ({ ok: true, text: async () => feed }));
  if (options.saved) w.localStorage.setItem('vox-reader-saved-v1', JSON.stringify(options.saved));
  ['vendor/purify.min.js', 'core.js'].forEach(file => w.eval(fs.readFileSync(path.join(root, file), 'utf8')));
  const start = () => w.eval(fs.readFileSync(path.join(root, 'app.js'), 'utf8'));
  return { dom, w, R: w.VoxReader, start, $: id => w.document.getElementById(id) };
}
const settle = () => new Promise(resolve => setTimeout(resolve, 20));
(async () => {
  const t = setup();
  const items = t.R.parse(feed);
  assert.equal(items.length, 3);
  assert.equal(items[0].title, 'Climate & context');
  assert.equal(items[2].published, '');
  assert.equal(t.R.select(items, 'energy climate', 'newest').length, 1);
  assert.equal(t.R.select(items, '', 'newest')[0].title, 'Science story');
  assert.equal(t.R.select(items, '', 'oldest')[0].title, 'Unknown date');
  assert.equal(t.R.sourceUrl('https://vox.com.evil.test/article'), '');
  assert.equal(t.R.sourceUrl('javascript:alert(1)'), '');
  assert.equal(t.R.url('https://user:pass@vox.com'), '');
  assert.equal(t.R.url(undefined), '');
  assert.equal(t.R.url(''), '');
  assert.throws(() => t.R.parse('<html><body>Error</body></html>'));
  assert.throws(() => t.R.parse('<feed>'));
  const safe = t.R.clean('<svg onload="alert(1)"></svg><form><input></form><img src="data:image/svg+xml,x"><p style="position:fixed" onclick="alert(1)">Safe</p>', 'https://www.vox.com');
  assert.ok(!/svg|onload|onclick|style=|data:|input|form/.test(safe));
  assert.ok(!/onerror|<script|<iframe|javascript:/.test(items[0].content));
  assert.ok(items[0].content.includes('rel="noopener noreferrer"'));
  const rss = t.R.parse('<rss><channel><item><title>RSS story</title><link>https://www.vox.com/rss-test</link><description>Text</description><pubDate>Wed, 07 Oct 2026 00:00:00 GMT</pubDate></item></channel></rss>');
  assert.equal(rss.length, 1);
  t.start(); await settle();
  assert.equal(t.$('stories').children.length, 3);
  assert.equal(t.$('article-title').textContent, 'Science story');
  assert.equal(t.$('stories').getAttribute('aria-busy'), 'false');
  assert.equal(t.$('source').target, '_blank');
  t.$('search').value = 'climate'; t.$('search').dispatchEvent(new t.w.Event('input'));
  assert.equal(t.$('stories').children.length, 1);
  t.$('stories').querySelector('.story-open').click();
  assert.equal(t.$('article-title').textContent, 'Climate & context');
  assert.ok(t.w.document.body.classList.contains('reader-open'));
  assert.equal(t.w.document.activeElement.id, 'article-title');
  t.$('save').click();
  assert.equal(t.$('saved-count').textContent, '1');
  assert.equal(JSON.parse(t.w.localStorage.getItem('vox-reader-saved-v1')).length, 1);
  assert.equal(t.$('save').getAttribute('aria-pressed'), 'true');
  t.$('saved').click();
  assert.equal(t.$('stories').children.length, 1);
  t.$('text-size').value = '20'; t.$('text-size').dispatchEvent(new t.w.Event('change'));
  assert.equal(t.w.document.documentElement.style.getPropertyValue('--reading-size'), '20px');
  t.$('back').click();
  assert.ok(!t.w.document.body.classList.contains('reader-open'));
  assert.ok(t.w.document.activeElement.classList.contains('story-open'));
  const stored = JSON.parse(t.w.localStorage.getItem('vox-reader-saved-v1'));
  const offline = setup({ saved: stored, fetch: async () => { throw new Error('Offline'); } });
  offline.start(); await settle();
  assert.equal(offline.$('saved').getAttribute('aria-pressed'), 'true');
  assert.equal(offline.$('article-title').textContent, 'Climate & context');
  assert.equal(offline.$('feed-status').dataset.error, 'true');
  const offlineLink = setup({ saved: [items[0], items[1]], fetch: async () => { throw new Error('Offline'); } });
  offlineLink.w.location.hash = '#story=' + encodeURIComponent(items[1].link);
  offlineLink.start(); await settle();
  assert.equal(offlineLink.$('article-title').textContent, 'Science story');
  assert.ok(offlineLink.w.document.body.classList.contains('reader-open'));
  offline.$('search').value = 'no-match'; offline.$('search').dispatchEvent(new offline.w.Event('input'));
  assert.match(offline.$('stories').textContent, /No matching/);
  Object.defineProperty(offline.w.Storage.prototype, 'setItem', { value: () => { throw new Error('Quota'); } });
  offline.$('save').click();
  assert.equal(offline.$('saved-count').textContent, '1');
  assert.match(offline.$('notice').textContent, /unchanged/);
  const failure = setup({ fetch: async () => ({ ok: true, text: async () => '<html>Not a feed</html>' }) });
  failure.start(); await settle();
  assert.match(failure.$('stories').textContent, /feed is unavailable/);
  assert.equal(failure.$('refresh').disabled, false);
  assert.ok(failure.$('stories').querySelector('button'));
  let calls = 0;
  const fallback = setup({ fetch: async () => { calls++; return { ok: true, text: async () => calls === 1 ? '<html>Error</html>' : feed }; } });
  fallback.start(); await settle();
  assert.equal(calls, 2);
  assert.equal(fallback.$('stories').children.length, 3);
  t.$('save').click();
  assert.equal(t.$('saved-count').textContent, '0');
  assert.equal(t.$('save').getAttribute('aria-pressed'), 'false');
  for (const instance of [t, offline, offlineLink, failure, fallback]) instance.dom.window.close();
  console.log('Passed: Atom/RSS parsing, markup sanitization, real feed fallbacks, search/sort, article selection, bookmarks, offline saved reading, storage errors, text size and navigation.');
})().catch(error => { console.error(error); process.exitCode = 1; });
